language: node_js
sudo: required
dist: trusty
node_js: stable
before_script:
- npm install --silent bower polymer-cli
- ./node_modules/.bin/bower install --silent
addons:
  sauce_connect: flase
script:
- npm run lint
cache:
  directories:
  - bower_components
  - node_modules
branches:
  only:
    - stage
    - develop
after_success:
  - node tasks/ci.js
